parameters:
    bk_core.contact_manager.class: BK\CoreBundle\Manager\ContactManager

services:
    bk_core.contact_manager:
        class: %bk_core.contact_manager.class%
        arguments: [@doctrine.orm.entity_manager, %segmentio_writekey%]
